import { BaseSeeder } from '@adonisjs/lucid/seeders'
import MenuItem from '#models/menu_item'

/** Minutes to seconds */
const min = (m: number) => Math.round(m * 60)

export default class extends BaseSeeder {
  async run() {
    const img = (code: string) => `/uploads/${code.toLowerCase()}.png`

    const items: Partial<MenuItem>[] = [
      // Appetizers (fryer)
      { code: 'E2', title: 'Chicken Egg Roll', station: 'fryer', batchSizes: ['1','2','3'], cookTimes: { '1': min(7), '2': min(7), '3': min(7) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'3', snack:'2', dinner:'3', late_snack:'2' }, imageUrl: img('e2'), color: 'green', ingredients: ['Cabbage','Carrots','Green onions','Chicken','Wonton wrapper'], allergens: ['Sesame','Milk','Eggs','Soybeans','Wheat'], nutrition: { serving_size_oz: 2.75, calories_kcal: 200, protein_g: 6, carbohydrate_g: 20, saturated_fat_g: 2 } },
      { code: 'E3', title: 'Cream Cheese Rangoon', station: 'fryer', batchSizes: ['1','2','3'], cookTimes: { '1': min(2.5), '2': min(2.5), '3': min(2.5) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'3', snack:'2', dinner:'3', late_snack:'2' }, imageUrl: img('e3'), color: 'green', ingredients: ['Cream cheese','Green onions','Wonton wrapper'], allergens: ['Milk','Eggs','Wheat','Soybeans'], nutrition: { serving_size_oz: 1.9, calories_kcal: 190, protein_g: 5, carbohydrate_g: 24, saturated_fat_g: 4 } },
      { code: 'E1', title: 'Veggie Spring Roll', station: 'fryer', batchSizes: ['1','2','3'], cookTimes: { '1': min(5), '2': min(5), '3': min(5) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'3', snack:'2', dinner:'3', late_snack:'2' }, imageUrl: img('e1'), color: 'green', ingredients: ['Cabbage','Carrots','Taro','Yam bean','Spring roll wrapper'], allergens: ['Wheat','Soybeans'], nutrition: { serving_size_oz: 1.9, calories_kcal: 130, protein_g: 2, carbohydrate_g: 19, saturated_fat_g: 1 } },
      // Beef
      { code: 'B5', title: 'Beijing Beef', station: 'fryer', batchSizes: ['1','2','3'], cookTimes: { '1': min(5), '2': min(5), '3': min(5) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'2', snack:'1', dinner:'2', late_snack:'1' }, imageUrl: img('b5'), color: 'red', ingredients: ['Beef','Red bell peppers','Onions','Orange peel','Chili peppers'], allergens: ['Eggs','Wheat','Soybeans'], nutrition: { serving_size_oz: 5.6, calories_kcal: 470, protein_g: 19, carbohydrate_g: 51, saturated_fat_g: 4.5 } },
      { code: 'B3', title: 'Black Pepper Sirloin Steak', station: 'stirfry', batchSizes: ['1','2','3'], cookTimes: { '1': min(1.5), '2': min(1.75), '3': min(2) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'2', snack:'1', dinner:'2', late_snack:'1' }, imageUrl: img('b3'), color: 'red', ingredients: ['Sirloin steak','Red bell peppers','Yellow onions','Mushrooms','Black pepper sauce'], allergens: ['Wheat','Soybeans'], nutrition: { serving_size_oz: 5.5, calories_kcal: 180, protein_g: 19, carbohydrate_g: 13, saturated_fat_g: 2 } },
      { code: 'B1', title: 'Broccoli Beef', station: 'stirfry', batchSizes: ['1','2','3'], cookTimes: { '1': min(0.75), '2': min(1), '3': min(1.25) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'2', snack:'1', dinner:'2', late_snack:'1' }, imageUrl: img('b1'), color: 'green', ingredients: ['Beef','Broccoli','Ginger','Garlic'], allergens: ['Wheat','Soybeans'], nutrition: { serving_size_oz: 5.4, calories_kcal: 150, protein_g: 9, carbohydrate_g: 13, saturated_fat_g: 1.5 } },
      // Chicken
      { code: 'C4', title: 'Grilled Teriyaki Chicken', station: 'grill', batchSizes: ['1','2','3'], cookTimes: { '1': min(7), '2': min(7), '3': min(7) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'2', snack:'1', dinner:'2', late_snack:'1' }, imageUrl: img('c4'), color: 'green', ingredients: ['Chicken thigh','Teriyaki sauce','Soy sauce','Ginger','Garlic'], allergens: ['Wheat','Soybeans'], nutrition: { serving_size_oz: 5.5, calories_kcal: 300, protein_g: 36, carbohydrate_g: 8, saturated_fat_g: 3.5 } },
      { code: 'CB3', title: 'Honey Sesame Chicken Breast', station: 'fryer', batchSizes: ['1','2','3'], cookTimes: { '1': min(2.5), '2': min(2.5), '3': min(2.5) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'2', snack:'1', dinner:'2', late_snack:'1' }, imageUrl: img('cb3'), color: 'green', ingredients: ['Chicken breast','Sesame seeds','Honey','String beans'], allergens: ['Sesame','Eggs','Wheat','Soybeans'], nutrition: { serving_size_oz: 5.6, calories_kcal: 420, protein_g: 17, carbohydrate_g: 57, saturated_fat_g: 2 } },
      { code: 'C3', title: 'Kung Pao Chicken', station: 'stirfry', batchSizes: ['1','2','3'], cookTimes: { '1': min(1.25), '2': min(1.5), '3': min(1.75) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'2', snack:'1', dinner:'2', late_snack:'1' }, imageUrl: img('c3'), color: 'green', ingredients: ['Chicken','Peanuts','Zucchini','Red bell peppers','Chili peppers'], allergens: ['Peanuts','Wheat','Soybeans'], nutrition: { serving_size_oz: 6, calories_kcal: 290, protein_g: 23, carbohydrate_g: 22, saturated_fat_g: 2 } },
      { code: 'C2', title: 'Mushroom Chicken', station: 'stirfry', batchSizes: ['1','2','3'], cookTimes: { '1': min(1.25), '2': min(1.5), '3': min(1.75) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'2', snack:'1', dinner:'2', late_snack:'1' }, imageUrl: img('c2'), color: 'yellow', ingredients: ['Chicken','Mushrooms','Zucchini','Water chestnuts'], allergens: ['Wheat','Soybeans'], nutrition: { serving_size_oz: 5.7, calories_kcal: 220, protein_g: 14, carbohydrate_g: 19, saturated_fat_g: 1.5 } },
      { code: 'C1', title: 'Orange Chicken', station: 'fryer', batchSizes: ['1','2','3'], cookTimes: { '1': min(8), '2': min(8), '3': min(8) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'2', snack:'1', dinner:'2', late_snack:'1' }, imageUrl: img('c1'), color: 'green', ingredients: ['Chicken','Orange sauce','Soy sauce','Ginger','Garlic'], allergens: ['Eggs','Wheat','Soybeans'], nutrition: { serving_size_oz: 5.7, calories_kcal: 490, protein_g: 25, carbohydrate_g: 51, saturated_fat_g: 3.5 } },
      { code: 'CB1', title: 'String Bean Chicken Breast', station: 'stirfry', batchSizes: ['1','2','3'], cookTimes: { '1': min(0.75), '2': min(1), '3': min(1.25) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'1', snack:'1', dinner:'1', late_snack:'1' }, imageUrl: img('cb1'), color: 'red', ingredients: ['Chicken breast','String beans','Onions','Ginger','Garlic'], allergens: ['Wheat','Soybeans'], nutrition: { serving_size_oz: 5.3, calories_kcal: 190, protein_g: 14, carbohydrate_g: 19, saturated_fat_g: 1 } },
      // Seafood
      { code: 'F4', title: 'Honey Walnut Shrimp', station: 'fryer', batchSizes: ['1','2','3'], cookTimes: { '1': min(3), '2': min(3), '3': min(3) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'2', snack:'1', dinner:'2', late_snack:'1' }, imageUrl: img('f4'), color: 'green', ingredients: ['Shrimp','Walnuts','Honey melon sauce','Mayonnaise'], allergens: ['Tree nuts','Milk','Eggs','Shellfish','Wheat','Soybeans'], nutrition: { serving_size_oz: 3.5, calories_kcal: 360, protein_g: 13, carbohydrate_g: 35, saturated_fat_g: 5 } },
      // Sides
      { code: 'M1', title: 'Chow Mein', station: 'sides', batchSizes: ['1','2','3'], cookTimes: { '1': min(7), '2': min(7), '3': min(7) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'2', snack:'1', dinner:'2', late_snack:'1' }, imageUrl: img('m1'), color: 'green', ingredients: ['Wheat noodles','Cabbage','Celery','Onions','Bean sprouts'], allergens: ['Wheat','Soybeans'], nutrition: { serving_size_oz: 9.4, calories_kcal: 510, protein_g: 14, carbohydrate_g: 85, saturated_fat_g: 1 } },
      { code: 'R1', title: 'Fried Rice', station: 'sides', batchSizes: ['1','2','3'], cookTimes: { '1': min(7), '2': min(7), '3': min(7) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'2', snack:'1', dinner:'2', late_snack:'1' }, imageUrl: img('r1'), color: 'green', ingredients: ['Rice','Eggs','Carrots','Peas','Green onions','Soy sauce'], allergens: ['Eggs','Wheat','Soybeans'], nutrition: { serving_size_oz: 9.3, calories_kcal: 620, protein_g: 13, carbohydrate_g: 93, saturated_fat_g: 2 } },
      { code: 'R2', title: 'White Rice', station: 'sides', batchSizes: ['1','2','3'], cookTimes: { '1': min(7), '2': min(7), '3': min(7) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'2', snack:'1', dinner:'2', late_snack:'1' }, imageUrl: img('r2'), color: 'green', ingredients: ['Steamed white rice'], allergens: [], nutrition: { serving_size_oz: 8.1, calories_kcal: 380, protein_g: 7, carbohydrate_g: 86, saturated_fat_g: 0 } },
      // Vegetable
      { code: 'V1', title: 'Super Greens', station: 'stirfry', batchSizes: ['1','2','3'], cookTimes: { '1': min(3), '2': min(3), '3': min(3) }, enabled: true, recommendedBatch: { breakfast:'1', lunch:'1', snack:'1', dinner:'2', late_snack:'1' }, imageUrl: img('v1'), color: 'red', ingredients: ['Broccoli','Kale','Cabbage','String beans','Ginger'], allergens: ['Wheat','Soybeans'], nutrition: { serving_size_oz: 7.5, calories_kcal: 130, protein_g: 7, carbohydrate_g: 19, saturated_fat_g: 0 } },
    ]
    for (const row of items) {
      await MenuItem.updateOrCreate({ code: row.code! }, row as any)
    }
  }
}
